In [1]:
import pandas as pd

In [2]:
readdict = {}
readdict[('County Code', 'Unnamed: 0_level_1', 'Unnamed: 0_level_2')] = str
readdict[('Voivodeship Code', 'Unnamed: 0_level_1', 'Unnamed: 0_level_2')] = str
readdict[('County Code','Unnamed: 0_level_1','Unnamed: 0_level_2','Unnamed: 0_level_3')] = str
readdict[('Voivodeship Code','Unnamed: 0_level_1','Unnamed: 0_level_2','Unnamed: 0_level_3')] = str
readdict[('County Code','Unnamed: 0_level_1','Unnamed: 0_level_2','Unnamed: 0_level_3','Unnamed: 0_level_4')] = str
readdict[('Voivodeship Code','Unnamed: 0_level_1','Unnamed: 0_level_2','Unnamed: 0_level_3','Unnamed: 0_level_4')] = str

# Mering files with 3 level MultiIndex

In [3]:
files3 = ['animal_stock_by_voivodship_dist.xlsx','area_by_land_use_by_voivodship_dist.xlsx','area_by_powiat.xlsx','emission_of_particulates_by_powiat.xlsx','emission_of_pollutant_gases_by_powiat.xlsx',\
          'forest_area_by_powiat.xlsx', 'plants_of_significant_nuisance_to_air_quality_by_voivodship_dist.xlsx', 'population_density_by_powiat.xlsx', 'production_of_electricity_by_sources_by_voivodship_dist.xlsx',\
            'share_of_green_areas_by_powiat.xlsx','share_of_urbanized_area_by_voivodship_dist.xlsx','total_vehicles_by_type_by_powiat.xlsx']

prefix3 = ['[animal stock]', '[area by land]', '[area]', '[emission of particulates]','[emission of pollutant gases]', '[forest area]','[plants of significant nuisance]',\
           '[population density]', '[production of electricity]', '[share of green areas]', '[share of urbanized areas]', '[total vehicles]']

key3 = [('County Code', 'Unnamed: 0_level_1','Unnamed: 0_level_2')]

In [4]:
def rename_columns(df, prefix):
    cols = {}
    for col in df.columns[4:]:
        if col[0] not in cols:
            cols[col[0]] = ' '.join([prefix,col[0]])
    return cols

def drop_duplicates(merged_df):
    cols_to_drop = []
    for col in merged_df.columns:
        if col[0].endswith('_right'):
            cols_to_drop.append(col)
    merged_df = merged_df.drop(columns=cols_to_drop)
    return merged_df

In [5]:
df = pd.read_excel("../../data/data_processed/static_annual_data/"+files3[0],header=[0,1,2], \
                   dtype = readdict)
df.head()

  Unnamed: 0_level_0        County Code            County Name  \
  Unnamed: 0_level_1 Unnamed: 0_level_1     Unnamed: 1_level_1
  Unnamed: 0_level_2 Unnamed: 0_level_2     Unnamed: 1_level_2
0                NaN                NaN                    NaN
1                0.0            0201000   powiat bolesławiecki
2                1.0            0202000  powiat dzierżoniowski
3                2.0            0203000       powiat głogowski
4                3.0            0204000        powiat górowski

    Voivodeship Code        Voivodeship        total                           \
  Unnamed: 0_level_1 Unnamed: 1_level_1 2017_by_area 2017_by_pop 2018_by_area
  Unnamed: 0_level_2 Unnamed: 1_level_2       [head]      [head]       [head]
0                NaN                NaN          NaN         NaN          NaN
1            0200000       dolnośląskie      13092.0      6210.0      14222.0
2            0200000       dolnośląskie       4809.0      7042.0       5224.0
3            0200000       dolnośląskie       4448.0      6207.0       4832.0
4            0200000       dolnośląskie       7409.0      2445.0       8049.0

                                                                              \
  2018_by_pop 2019_by_area 2019_by_pop 2020_by_area 2020_by_pop 2021_by_area
       [head]       [head]      [head]       [head]      [head]       [head]
0         NaN          NaN         NaN          NaN         NaN          NaN
1      6746.0      13746.0      6528.0      13791.0      6428.0      12186.0
2      7613.0       5050.0      7333.0       5066.0      7118.0       4476.0
3      6709.0       4670.0      6460.0       4685.0      6294.0       4140.0
4      2656.0       7780.0      2517.0       7805.0      2407.0       6897.0


  2021_by_pop
       [head]
0         NaN
1      5703.0
2      6223.0
3      5556.0
4      2136.0

In [6]:
#Remove first column, add prefix and remove first row
df.drop(columns=df.columns[0],inplace=True)
df.rename(columns=rename_columns(df,prefix3[0]),inplace=True)
df.drop(index=0,inplace=True)

In [7]:
#add isUrban feature
df['isUrban','Unnamed: 0_level_1','Unnamed: 0_level_2'] = \
    [1 if x[7].isupper() else 0 for x in df['County Name', 'Unnamed: 1_level_1', 'Unnamed: 1_level_2']]

In [8]:
m3df= df
for i,fname in enumerate(files3):
    if i==0:
        continue
    df2 = pd.read_excel("../../data/data_processed/static_annual_data/"+fname, header=[0,1,2], \
                   dtype = readdict)
    df2.drop(columns=df2.columns[0],inplace=True)
    df2.rename(columns=rename_columns(df2,prefix3[i]),inplace=True)
    df2.drop(index=0,inplace=True)
    #merge
    m3df = pd.merge(m3df,df2,on=key3,suffixes=[None,"_right"],validate="1:1")
    m3df = drop_duplicates(m3df)

# Mering files with 4 level MultiIndex

In [9]:
files4 = ['air_pollution_reduction_systems_in_plants_by_voivodship_dist.xlsx', 'forest_fires_by_voivodship_dist.xlsx', 'vehicles_by_type_and_fuel_by powiat.xlsx']

prefix4 = ['[air pollution reduction systems]', '[forest fires]', '[vehicles by type and fuel]']

key4 = [('County Code', 'Unnamed: 0_level_1','Unnamed: 0_level_2','Unnamed: 0_level_3')]

In [10]:
df = pd.read_excel("../../data/data_processed/static_annual_data/"+files4[0],header=[0,1,2,3], \
                   dtype = readdict)
df.head()

  Unnamed: 0_level_0        County Code            County Name  \
  Unnamed: 0_level_1 Unnamed: 0_level_1     Unnamed: 1_level_1
  Unnamed: 0_level_2 Unnamed: 0_level_2     Unnamed: 1_level_2
  Unnamed: 0_level_3 Unnamed: 0_level_3     Unnamed: 1_level_3
0                NaN                NaN                    NaN
1                0.0            0201000   powiat bolesławiecki
2                1.0            0202000  powiat dzierżoniowski
3                2.0            0203000       powiat głogowski
4                3.0            0204000        powiat górowski

    Voivodeship Code        Voivodeship        cyclones              \
  Unnamed: 0_level_1 Unnamed: 1_level_1 equipment total
  Unnamed: 0_level_2 Unnamed: 1_level_2    2017_by_area 2017_by_pop
  Unnamed: 0_level_3 Unnamed: 1_level_3           [pcs]       [pcs]
0                NaN                NaN             NaN         NaN
1            0200000       dolnośląskie             8.0         4.0
2            0200000       dolnośląskie             3.0         5.0
3            0200000       dolnośląskie             3.0         4.0
4            0200000       dolnośląskie             5.0         2.0

                                         ...               others              \
                                         ... total waste gas flow
  2018_by_area 2018_by_pop 2019_by_area  ...         2017_by_area 2017_by_pop
         [pcs]       [pcs]        [pcs]  ...             [dam3/h]    [dam3/h]
0          NaN         NaN          NaN  ...                  NaN         NaN
1          8.0         4.0          7.0  ...                177.0        84.0
2          3.0         4.0          3.0  ...                 65.0        95.0
3          3.0         4.0          2.0  ...                 60.0        84.0
4          5.0         1.0          4.0  ...                100.0        33.0

                                                                              \

  2018_by_area 2018_by_pop 2019_by_area 2019_by_pop 2020_by_area 2020_by_pop
      [dam3/h]    [dam3/h]     [dam3/h]    [dam3/h]     [dam3/h]    [dam3/h]
0          NaN         NaN          NaN         NaN          NaN         NaN
1        182.0        86.0        132.0        63.0        120.0        56.0
2         67.0        97.0         48.0        70.0         44.0        62.0
3         62.0        86.0         45.0        62.0         41.0        55.0
4        103.0        34.0         75.0        24.0         68.0        21.0



  2021_by_area 2021_by_pop
      [dam3/h]    [dam3/h]
0          NaN         NaN
1        119.0        56.0
2         44.0        61.0
3         40.0        54.0
4         67.0        21.0

[5 rows x 425 columns]

In [11]:
#Remove first column, add prefix and remove first row
df.drop(columns=df.columns[0],inplace=True)
df.rename(columns=rename_columns(df,prefix4[0]),inplace=True)
df.drop(index=0,inplace=True)

In [12]:
m4df= df
for i,fname in enumerate(files4):
    if i==0:
        continue
    df2 = pd.read_excel("../../data/data_processed/static_annual_data/"+fname, header=[0,1,2,3], \
                   dtype = readdict)
    df2.drop(columns=df2.columns[0],inplace=True)
    df2.rename(columns=rename_columns(df2,prefix4[i]),inplace=True)
    df2.drop(index=0,inplace=True)
    #merge
    m4df = pd.merge(m4df,df2,on=key4,suffixes=[None,"_right"],validate="1:1")
    m4df = drop_duplicates(m4df)

# Mering files with 5 level MultiIndex

In [13]:
files5 = ['crop_production_by_voivodship_dist.xlsx']

prefix5= ['[crop production]']

key5 = [('County Code', 'Unnamed: 0_level_1','Unnamed: 0_level_2','Unnamed: 0_level_3','Unnamed: 0_level_4')]

In [14]:
df = pd.read_excel("../../data/data_processed/static_annual_data/"+files5[0],header=[0,1,2,3,4], \
                   dtype = readdict)
df.head()

  Unnamed: 0_level_0        County Code            County Name  \
  Unnamed: 0_level_1 Unnamed: 0_level_1     Unnamed: 1_level_1
  Unnamed: 0_level_2 Unnamed: 0_level_2     Unnamed: 1_level_2
  Unnamed: 0_level_3 Unnamed: 0_level_3     Unnamed: 1_level_3
  Unnamed: 0_level_4 Unnamed: 0_level_4     Unnamed: 1_level_4
0                NaN                NaN                    NaN
1                0.0            0201000   powiat bolesławiecki
2                1.0            0202000  powiat dzierżoniowski
3                2.0            0203000       powiat głogowski
4                3.0            0204000        powiat górowski

    Voivodeship Code        Voivodeship cereals, grand total              \
  Unnamed: 0_level_1 Unnamed: 1_level_1           area in ha
  Unnamed: 0_level_2 Unnamed: 1_level_2                total
  Unnamed: 0_level_3 Unnamed: 1_level_3         2017_by_area 2017_by_pop
  Unnamed: 0_level_4 Unnamed: 1_level_4                 [ha]        [ha]
0                NaN                NaN                  NaN         NaN
1            0200000       dolnośląskie              34712.0     16466.0
2            0200000       dolnośląskie              12751.0     18671.0
3            0200000       dolnośląskie              11793.0     16458.0
4            0200000       dolnośląskie              19645.0      6483.0

                                         ... permanent pastures              \
                                         ...         area in ha
                                         ...              total
  2018_by_area 2018_by_pop 2019_by_area  ...       2017_by_area 2017_by_pop
          [ha]        [ha]         [ha]  ...               [ha]        [ha]
0          NaN         NaN          NaN  ...                NaN         NaN
1      31746.0     15057.0      35261.0  ...             1264.0       599.0
2      11662.0     16993.0      12953.0  ...              464.0       680.0
3      10785.0     14975.0      11979.0  ...              429.0       599.0
4      17967.0      5928.0      19956.0  ...              715.0       236.0

                                                                              \


  2018_by_area 2018_by_pop 2019_by_area 2019_by_pop 2020_by_area 2020_by_pop
          [ha]        [ha]         [ha]        [ha]         [ha]        [ha]
0          NaN         NaN          NaN         NaN          NaN         NaN
1       1267.0       601.0       1222.0       580.0       1297.0       604.0
2        465.0       678.0        449.0       652.0        476.0       669.0
3        430.0       598.0        415.0       574.0        441.0       592.0
4        717.0       237.0        692.0       224.0        734.0       226.0




  2021_by_area 2021_by_pop
          [ha]        [ha]
0          NaN         NaN
1       2094.0       980.0
2        769.0      1069.0
3        711.0       955.0
4       1185.0       367.0

[5 rows x 65 columns]

In [15]:
#Remove first column, add prefix and remove first row
df.drop(columns=df.columns[0],inplace=True)
df.rename(columns=rename_columns(df,prefix5[0]),inplace=True)
df.drop(index=0,inplace=True)
m5df = df

# Expand all MultiIndex to 5 levels

Convention: 
* first level contains the name with the prefix,
* last level contains unit
* penultimate level contains the year
* the rest is filled with blank levels

In [16]:
m3df_newmi = []
for i, t in enumerate(m3df.columns):
    if t[0] in ['County Code', 'Voivodeship Code','isUrban'] :
        temp = list(t) + ['Unnamed: 0_level_3','Unnamed: 0_level_4']
        m3df_newmi.append(tuple(temp))
    elif t[0] in ['County Name', 'Voivodeship']:
        temp = list(t) + ['Unnamed: 1_level_3','Unnamed: 1_level_4']
        m3df_newmi.append(tuple(temp))
    else:
        temp = list(t)
        assert len(temp) == 3
        temp_list = [temp[0], 'Unnamed: 0_level_1', 'Unnamed: 0_level_2', temp[1], temp[2]]
        m3df_newmi.append(tuple(temp_list))

ind = m3df_newmi.index(('isUrban', 'Unnamed: 0_level_1', 'Unnamed: 0_level_2', 'Unnamed: 0_level_3', 'Unnamed: 0_level_4'))
m3df_newmi = pd.MultiIndex.from_tuples(m3df_newmi)

In [17]:
m4df_newmi = []
for i, t in enumerate(m4df.columns):
    if i < 4:
        if t[0] in ['County Code', 'Voivodeship Code']:
            temp = list(t) + ['Unnamed: 0_level_4']
        elif t[0] in ['County Name', 'Voivodeship']:
            temp = list(t) + ['Unnamed: 1_level_4']
        m4df_newmi.append(tuple(temp))
    else:
        temp = list(t)
        assert len(temp) == 4
        temp_list = [temp[0], 'Unnamed: 0_level_1', temp[1], temp[2], temp[3]]
        m4df_newmi.append(tuple(temp_list))
m4df_newmi = pd.MultiIndex.from_tuples(m4df_newmi)

In [18]:
m3df.columns = m3df_newmi
m4df.columns = m4df_newmi

# Merge all data

In [19]:
static_final = pd.merge(m3df,m4df,on=key5,suffixes=[None,"_right"],validate="1:1")
static_final = drop_duplicates(static_final)
static_final = pd.merge(static_final,m5df,on=key5,suffixes=[None,"_right"],validate="1:1")
static_final = drop_duplicates(static_final)

In [20]:
#reorder columns
isUrbanColName = static_final.columns[ind]
isUrbanValues = static_final.iloc[:,ind]
static_final.drop(columns = [isUrbanColName],inplace=True)
static_final.insert(loc=4, column=isUrbanColName, value=isUrbanValues)

In [21]:
#save the data
static_final.to_excel(f'../../data/data_processed/static_annual_data/combined_static_annual_data.xlsx')